api/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from rest_framework.generics import ListCreateAPIView

from .views import *
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('', ApiRoot.as_view(),name='api-root'),
    # path('employees/list/', EmployeeListApiView.as_view(),name='employee-list'),
    # path('employees/add/', EmployeeCreateApiView.as_view(),name='employee-add'),
    # path('subcontractors/list/', SubcontractorListApiView.as_view(),name='subcontractor-list'),
    # path('subcontractors/add/', SubcontractorCreateApiView.as_view(),name='subcontractor-add'),
    # path('subcontractors/view/(?P<pk>[0-9]+)/', SubcontractorRetrieveView.as_view(),name='subcontractor-view'),
    # path('subcontractors/edit/(?P<pk>\d+)/$', SubcontractorUpdateAPIView.as_view(),name='subcontractor-edit'),
	# path('logout/$', log_out, name='logout'),

]

cleaning_crm/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include,re_path
from django.conf.urls.i18n import i18n_patterns
from django.views import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views.static import serve
from django.contrib.auth.decorators import login_required


from core import set_lang as core_views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('administration/', admin.site.urls,name="admin"),

    # path(r'api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),

    path('api/v1/', include("api.urls"), name="api"),
    path('api/v1/chat/', include('chat.uris')),
    path('api/v1/customer/', include('api_customer.urls',namespace="customer-api")),
    path('api/v1/employee/', include('api_employee.urls',namespace="employee-api")),
    path('api/v1/administration/', include('api_administration.urls',namespace="administration-api")),
    # path(r'api-token-auth/', obtain_jwt_token),
    # path(r'api-token-refresh/', refresh_jwt_token),
    # path(r'api-token-verify/', verify_jwt_token),

    # path(r'tinymce/', include('tinymce.urls')),
     path(r'summernote/', include('django_summernote.urls')),
    # path(r'ckeditor/', include('ckeditor_uploader.urls')),
        path(r'media/(?P<path>.*)', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
]
translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
    # path(r'test/$', index, name="index"),
    path('set-language/',core_views.set_language,  name='set_language'),
    # path(r'', include("timeopt.core.urls", namespace="core")),
    # path('api/', include('chat.uris')),
    path('', include('home.urls', namespace='home')),
    # path('', include("home.urls",namespace='home')),
    path('', include("work.urls", namespace="work")),
    path('auth-user/', include("base_user.urls", namespace="base-user")),
    path('messenger/', include("messenger.urls", namespace="messenger")),
    path('general/', include("general.urls", namespace="general")),

    # path(r'', include("tour.urls", namespace="tour")),
    # path(r'', include("userprofile.urls", namespace="userprofile")),
    # path(r'account/', include("base_user.urls", namespace="account")),
)

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        path(r'static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        path(r'media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

work/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from work.ajax_view import get_snippet_ajax
from work.calculate import task_calculate
from .views import *
from .plan_views import *

app_name = 'work'
urlpatterns = [
	path('change/password/', change_password, name='change-password'),

	path('admins/list/', admin_list, name='admin-list'),
    path('admins/add/', admin_add, name='admin-add'),
    path('admins/edit/<int:u_id>/', admin_edit, name='admin-edit'),
    path('admins/remove/<int:u_id>/', admin_remove, name='admin-remove'),
    path('user/profile/show/<int:ec_id>/', user_profile, name='user-profile'),
    # path('customers/remove/<int:c_id>/', customer_remove, name='customer-remove'),

	path('customers/list/<slug:op_slug>/', customers_list, name='customers-list'),
	path('customers/upload-from-excel/form/', customer_upload_from_excel, name='customer-upload-from-excel'),
	path('customers/payments/list/', customers_payment_list, name='customers-payment-list'),
	path('customers/payments/all/list/', all_payment_list, name='all-payments-list'),
    path('customers/add/', customer_add, name='customer-add'),
    path('customers/add-or-edit/card/', customer_add_card, name='customer-add-edit-card'),
    path('customers/edit/<int:c_id>/', customer_edit, name='customer-edit'),
    path('customers/remove/<int:c_id>/', customer_remove, name='customer-remove'),

    path('employees/list/<slug:op_slug>/', employees_list, name='employees-list'),
	path('employees/add/', employee_add, name='employee-add'),
	path('employees/edit/<int:e_id>/', employee_edit, name='employee-edit'),
	path('employees/remove/<int:e_id>/', employee_remove, name='employee-remove'),

	# path('employees/add/', employee_add, name='employee-add'),
    path('teams/list/', teams_list, name='teams-list'),
	path('teams/add/', team_add, name='team-add'),
	path('teams/edit/<int:t_id>/', team_edit, name='team-edit'),
	path('teams/remove/<int:t_id>/', team_remove, name='team-remove'),

    path('subcontractors/list/<slug:op_slug>', subcontractors_list, name='subcontractors-list'),
    path('subcontractors/add/', subcontractors_add, name='subcontractor-add'),
    path('subcontractors/edit/<int:s_id>/', subcontractor_edit, name='subcontractor-edit'),
    path('subcontractors/remove/<int:s_id>/', subcontractor_remove, name='subcontractor-remove'),

    path('complaints/list/', complaints_list, name='complaints-list'),
    path('complaints/write/', complaint_add, name='complaint-add'),
    path('complaints/edit/<int:c_id>/', complaint_edit, name='complaints-edit'),
    path('complaints/remove/<int:c_id>/', complaint_remove, name='complaint-remove'),

    # path('work-plans/list/', work_plan, name='work-plan'),

    path('reminders/list/', reminders_list, name='reminders-list'),
	path('reminders/add/', reminder_add, name='reminder-add'),
	path('reminders/edit/<int:r_id>/', reminder_edit, name='reminder-edit'),
	path('reminders/remove/<int:r_id>/', reminder_remove, name='reminder-remove'),

    path('tasks/list/', tasks_list, name='tasks-list'),
    path('tasks/calculate/', task_calculate, name='tasks-calculate'),
	path('tasks/add/', task_add, name='task-add'),
	path('tasks/edit/<int:t_id>/', task_edit, name='task-edit'),
	path('tasks/remove/<int:t_id>/', task_remove, name='task-remove'),

    path('services/list/', services_list, name='services-list'),
	path('services/add/', service_add, name='service-add'),
	path('services/edit/<int:s_id>/', service_edit, name='service-edit'),
	path('services/remove/<int:s_id>/', service_remove, name='service-remove'),

    path('cleaning-programs/list/', cleaning_programs_list, name='cleaning-programs-list'),
	path('cleaning-programs/add/', cleaning_program_add, name='cleaning-program-add'),
	path('cleaning-programs/edit/<int:c_id>/', cleaning_program_edit, name='cleaning-program-edit'),
	path('cleaning-programs/remove/<int:c_id>/', cleaning_program_remove, name='cleaning-program-remove'),

    path('snippets/list/', snippets_list, name='snippets-list'),
    path('get-snippet/ajax/<slug:f_slug>/', get_snippet_ajax, name='get-snippet-ajax'),
	path('snippets/add/', snippet_add, name='snippet-add'),
	path('snippets/edit/<int:s_id>/', snippet_edit, name='snippet-edit'),
	path('snippets/remove/<int:s_id>/', snippet_remove, name='snippet-remove'),

    path('notes/list/', notes_list, name='notes-list'),
	path('notes/add/', note_add, name='note-add'),
	path('notes/edit/<int:n_id>/', note_edit, name='note-edit'),
	path('notes/view/<int:n_id>/', note_view, name='note-view'),
	path('notes/remove/<int:n_id>/', note_remove, name='note-remove'),

	path('contract/template/', contract_template_list, name='contract-template'),

	path('contract-template/list/', contract_template_list, name='contract-template-list'),
    path('contract-template/add/', contract_template_add, name='contract-template-add'),
    path('contract-template/edit/<int:c_id>/', contract_template_edit, name='contract-template-edit'),
    path('contract-template/view/<int:c_id>/', customer_edit, name='contract-template-view'),
    path('contract-template/remove/<int:c_id>/', customer_remove, name='contract-template-remove'),

    path('contract/confirm/<uuid:tc_id>/', contract_confirm, name='contract-confirm'),
    path('contract/confirm-success/', contract_confirm_success, name='contract-confirm-success'),

	path('calendar/show/', calendar, name='calendar-show'),
	path('calendar/calendar-customer-task-remove/<int:td_id>/', calendar_remove, name='calendar-customer-task-remove'),
	path('economy/chart/', economy, name='economy-chart'),
	path('salary/info/', salary, name='salary-info'),



	path('teams/plans/team/<int:t_id>/', admin_team_plans, name='admin-team-plans'),
	path('teams/plans/list/', team_plans, name='team-plans'),
	path('teams/plans/show/ajax/', team_plan_show_ajax, name='team-plan-show-ajax'),
	path('teams/plans/show/plan-map/ajax/', team_plan_show_map_ajax, name='team-plan-map-ajax'),

	path('d/admin-team-plan-form-generate/ajax/', admin_team_plan_form_generate_ajax, name='admin-team-plan-form-generate-ajax'),
	path('d/admin-team-plan-form-change-customer-position-ajax/ajax/<int:cur_cus_ord_id>/',
		admin_team_plan_form_change_customer_position_ajax, name='admin-change-customer-position-ajax'),
	path('d/admin-team-plan-form-customer-ajax/ajax/<int:e_p_id>/<int:l_id>/', admin_team_plan_form_customer_ajax, name='admin-team-plan-form-customer-ajax'),
]

templates/work/include/teams/plan/_direction_map.html
{% load static %}


    <style>
      #map {
{#        height: 100%;#}
        float: left;
        width: 100%;
        height: 500px;
      }
      #total {
        padding: 7px;
        margin: 0 0px 10px 0px;
        border-bottom: 2px dashed #26c281;
        border-top: 2px dashed #26c281;
        text-align: center;
        font-weight: 700;
        color: #333;
        font-size: 18px;
        background: azure;
      }
    </style>
    <div id="total"></div>
    <div id="map"></div>

    <script>
function initMap() {
    var $general_start_point = "";
    var $general_end_point = "";
{#    var $list = {{ map_data }};#}
    {% for map_data_item in map_data %}{% if forloop.first %} $general_start_point = "{{ map_data_item.0 }}"; {% endif %}{% if forloop.last %}$general_end_point = "{{ map_data_item.0 }}";{% endif %}{% endfor %}

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 4,
{#    center: {lat: -24.345, lng: 134.46}  // Australia.#}
  });

  var directionsService = new google.maps.DirectionsService;
  var directionsDisplay = new google.maps.DirectionsRenderer({
    draggable: true,
    map: map,
    panel: document.getElementById('right-panel')
  });

  directionsDisplay.addListener('directions_changed', function() {
    computeTotalDistance(directionsDisplay.getDirections());
  });

  displayRoute($general_start_point, $general_end_point, directionsService,
      directionsDisplay);
}

function displayRoute(origin, destination, service, display) {
    var $general_waypoints = [
                        {% for map_data_item in map_data %}
                            {% if forloop.first or forloop.last %}{% else %}{location: "{{ map_data_item.0 }}"},{% endif %}
                        {% endfor %}
    ];
  service.route({
    origin: origin,
    destination: destination,
    waypoints: $general_waypoints,
    travelMode: 'DRIVING',
    avoidTolls: true
  }, function(response, status) {
    if (status === 'OK') {
      display.setDirections(response);
    } else {
      alert('Could not display directions due to: ' + status);
    }
  });
}

function computeTotalDistance(result) {
  var total = 0;
  var myroute = result.routes[0];
  for (var i = 0; i < myroute.legs.length; i++) {
    total += myroute.legs[i].distance.value;
  }
  total = total / 1000;
  document.getElementById('total').innerHTML = total + ' km';
}
    </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDvv-kFV2Ql4HFcTVOUbyoU0qXjO_GFvs&callback=initMap"></script>

templates/work/include/teams/plan/_team_plans.html
{% load static %}
{% load i18n %}
    <li class="list-item border bottom {{ team_get_plans_w_d }} {% if forloop.counter == 1 %}active{% endif %}">
        <a href="javascript:void(0);" class="media-hover p-20">
            <div class="media-img">
                <img src="{% static 'main/dist/assets/images/avatars/default-user.png' %}" alt="">
            </div>
            <div class="info">
                <span class="title">{{ team_get_plans_w_d_get_customer.customer.get_customer_name }}</span>
                <span class="sub-title">{{ team_get_plans_w_d_get_customer.customer.address }}</span>
                <span class="float-item font-size-11 p-t-5">{{ team_get_plans_w_d_get_customer_minute }} {% trans 'Minutes' %}</span>
            </div>
            {% if profile_type and profile_type == 1 %}
                <div class="info">
                <hr>
                    <span class="title">
                        <button onclick="showOtherPlans('{% url 'work:admin-team-plan-form-generate-ajax' %}',{{ team_get_plans_w_d.id }},{{ team_get_plans_w_d_get_customer.customer.id }},'{% url 'work:admin-team-plan-form-customer-ajax' team_get_plans_w_d.id team_get_plans_w_d_get_customer.customer_id %}','{% url 'work:admin-change-customer-position-ajax' team_get_plans_w_d_get_customer.id  %}')" type="button" class="btn btn-primary btn-rounded btn-outline btn-block" data-toggle="modal" data-target="#edit-customer-order-modal">
                            <i class="fa fa-edit"></i>
                            {% trans 'Edit' %}
                        </button>
                    </span>
                </div>
            {% endif %}
        </a>
    </li>

templates/work/include/teams/plan/_team_plans_button.html
{% load i18n %}
<li class="list-item border bottom">
    <button id="show-map-button" data-ajax-url=""
            onclick="showPlanMap('{% url 'work:team-plan-map-ajax' %}',{{ team_get_plans_w_d_customer_list }})"
            class="offset-md-3 col-md-6 btn btn-info btn-rounded btn-outline"  data-toggle="modal" data-target="#show-map-modal">
        {% trans 'Look' %}
    </button>
    <h3 class="todo-blue"></h3>
</li>

templates/work/include/teams/plan/_week_part.html
{% load i18n %}
        <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{% trans 'Week' %}: {{ week_item }}
                    | {% trans 'Day' %}: {{ get_day_name }} </h4>
                </div>
                <ul class="list-media">