api/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from rest_framework.generics import ListCreateAPIView

from .views import *
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('', ApiRoot.as_view(),name='api-root'),
    # path('employees/list/', EmployeeListApiView.as_view(),name='employee-list'),
    # path('employees/add/', EmployeeCreateApiView.as_view(),name='employee-add'),
    # path('subcontractors/list/', SubcontractorListApiView.as_view(),name='subcontractor-list'),
    # path('subcontractors/add/', SubcontractorCreateApiView.as_view(),name='subcontractor-add'),
    # path('subcontractors/view/(?P<pk>[0-9]+)/', SubcontractorRetrieveView.as_view(),name='subcontractor-view'),
    # path('subcontractors/edit/(?P<pk>\d+)/$', SubcontractorUpdateAPIView.as_view(),name='subcontractor-edit'),
	# path('logout/$', log_out, name='logout'),

]

cleaning_crm/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include,re_path
from django.conf.urls.i18n import i18n_patterns
from django.views import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views.static import serve
from django.contrib.auth.decorators import login_required


from core import set_lang as core_views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('administration/', admin.site.urls,name="admin"),

    # path(r'api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),

    path('api/v1/', include("api.urls"), name="api"),
    path('api/v1/chat/', include('chat.uris')),
    path('api/v1/customer/', include('api_customer.urls',namespace="customer-api")),
    path('api/v1/employee/', include('api_employee.urls',namespace="employee-api")),
    path('api/v1/administration/', include('api_administration.urls',namespace="administration-api")),
    # path(r'api-token-auth/', obtain_jwt_token),
    # path(r'api-token-refresh/', refresh_jwt_token),
    # path(r'api-token-verify/', verify_jwt_token),

    # path(r'tinymce/', include('tinymce.urls')),
     path(r'summernote/', include('django_summernote.urls')),
    # path(r'ckeditor/', include('ckeditor_uploader.urls')),
        path(r'media/(?P<path>.*)', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
]
translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
    # path(r'test/$', index, name="index"),
    path('set-language/',core_views.set_language,  name='set_language'),
    # path(r'', include("timeopt.core.urls", namespace="core")),
    # path('api/', include('chat.uris')),
    path('', include('home.urls', namespace='home')),
    # path('', include("home.urls",namespace='home')),
    path('', include("work.urls", namespace="work")),
    path('auth-user/', include("base_user.urls", namespace="base-user")),
    path('messenger/', include("messenger.urls", namespace="messenger")),
    path('general/', include("general.urls", namespace="general")),

    # path(r'', include("tour.urls", namespace="tour")),
    # path(r'', include("userprofile.urls", namespace="userprofile")),
    # path(r'account/', include("base_user.urls", namespace="account")),
)

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        path(r'static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        path(r'media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/urls.py
# from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from django.urls import path
from .views import *

app_name = 'home'
urlpatterns = [
	path('', dashboard, name='dashboard'),
	path('home-test/', home_test, name='home-test'),
    # url(r'^sign-in/$', sign_in, name='sign_in'),
    # url(r'^d/change-password/$', change_password, name='change-password'),
    # url(r'^$', dashboard, name='dashboard'),
    # url(r'^d/plan-prepare/$', plan_prepare, name='plan-prepare'),
    # url(r'^d/plan-prepare/ajax/(?P<op_slug>[\w-]+)/$', plan_prepare_ajax, name='plan-prepare-ajax'),
    # url(r'^d/employee-show-plan/ajax/$', employee_plan_show_ajax, name='employee-plan-ajax'),
    # url(r'^d/admin-customers-from-excel/$', customer_upload_from_excel, name='admin-customers-upload-from-excel'),
    # url(r'^d/admin-employee-show-plan/ajax/(?P<e_id>[0-9]+)/$', admin_employee_plan_show_ajax, name='admin-employee-plan-ajax'),
    # url(r'^d/admin-employee-plan-form-generate/ajax/$', admin_employee_plan_form_generate_ajax, name='admin-employee-plan-form-generate-ajax'),
    # url(r'^d/admin-employee-plan-form-customers-ajax/ajax/(?P<e_p_id>[0-9]+)/(?P<l_id>[0-9]+)/$', admin_employee_plan_form_location_ajax, name='admin-employee-plan-form-location-ajax'),
    # url(r'^d/admin-employee-plan-form-change-location-position-ajax/ajax/(?P<cur_loc_ord_id>[0-9]+)/$', admin_employee_plan_form_change_location_position_ajax, name='admin-change-customers-position-ajax'),
    # url(r'^d/admin-employee-show-map-plan/ajax/$', admin_employee_plan_show_map_ajax, name='admin-employee-plan-map-ajax'),
    # url(r'^d/admin-all-employees-plans/$', admin_all_employees_plans, name='admin-all-employees-plans'),
    # url(r'^d/admin-all-customers/$', admin_all_customers, name='admin-all-customers'),
    # url(r'^d/admin-all-employees-plans/employee/(?P<e_id>[0-9]+)/$', admin_employee_plans, name='admin-employee-plans'),
    # url(r'^d/all-plans/$', all_plans, name='all-plans'),
    # url(r'^d/my-plans/$', my_plans, name='my-plans'),
    # # url(r'^forgot-password/$', forgot_password, name='forgot_password'),
    #
    # # url(r'^contact/$', 'home.views.contact',name='contact'),

]

work/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from work.ajax_view import get_snippet_ajax
from work.calculate import task_calculate
from .views import *
from .plan_views import *

app_name = 'work'
urlpatterns = [
	path('change/password/', change_password, name='change-password'),

	path('admins/list/', admin_list, name='admin-list'),
    path('admins/add/', admin_add, name='admin-add'),
    path('admins/edit/<int:u_id>/', admin_edit, name='admin-edit'),
    path('admins/remove/<int:u_id>/', admin_remove, name='admin-remove'),
    path('user/profile/show/<int:ec_id>/', user_profile, name='user-profile'),
    # path('customers/remove/<int:c_id>/', customer_remove, name='customer-remove'),

	path('customers/list/<slug:op_slug>/', customers_list, name='customers-list'),
	path('customers/upload-from-excel/form/', customer_upload_from_excel, name='customer-upload-from-excel'),
	path('customers/payments/list/', customers_payment_list, name='customers-payment-list'),
	path('customers/payments/all/list/', all_payment_list, name='all-payments-list'),
    path('customers/add/', customer_add, name='customer-add'),
    path('customers/add-or-edit/card/', customer_add_card, name='customer-add-edit-card'),
    path('customers/edit/<int:c_id>/', customer_edit, name='customer-edit'),
    path('customers/remove/<int:c_id>/', customer_remove, name='customer-remove'),

    path('employees/list/<slug:op_slug>/', employees_list, name='employees-list'),
	path('employees/add/', employee_add, name='employee-add'),
	path('employees/edit/<int:e_id>/', employee_edit, name='employee-edit'),
	path('employees/remove/<int:e_id>/', employee_remove, name='employee-remove'),

	# path('employees/add/', employee_add, name='employee-add'),
    path('teams/list/', teams_list, name='teams-list'),
	path('teams/add/', team_add, name='team-add'),
	path('teams/edit/<int:t_id>/', team_edit, name='team-edit'),
	path('teams/remove/<int:t_id>/', team_remove, name='team-remove'),

    path('subcontractors/list/<slug:op_slug>', subcontractors_list, name='subcontractors-list'),
    path('subcontractors/add/', subcontractors_add, name='subcontractor-add'),
    path('subcontractors/edit/<int:s_id>/', subcontractor_edit, name='subcontractor-edit'),
    path('subcontractors/remove/<int:s_id>/', subcontractor_remove, name='subcontractor-remove'),

    path('complaints/list/', complaints_list, name='complaints-list'),
    path('complaints/write/', complaint_add, name='complaint-add'),
    path('complaints/edit/<int:c_id>/', complaint_edit, name='complaints-edit'),
    path('complaints/remove/<int:c_id>/', complaint_remove, name='complaint-remove'),

    # path('work-plans/list/', work_plan, name='work-plan'),

    path('reminders/list/', reminders_list, name='reminders-list'),
	path('reminders/add/', reminder_add, name='reminder-add'),
	path('reminders/edit/<int:r_id>/', reminder_edit, name='reminder-edit'),
	path('reminders/remove/<int:r_id>/', reminder_remove, name='reminder-remove'),

    path('tasks/list/', tasks_list, name='tasks-list'),
    path('tasks/calculate/', task_calculate, name='tasks-calculate'),
	path('tasks/add/', task_add, name='task-add'),
	path('tasks/edit/<int:t_id>/', task_edit, name='task-edit'),
	path('tasks/remove/<int:t_id>/', task_remove, name='task-remove'),

    path('services/list/', services_list, name='services-list'),
	path('services/add/', service_add, name='service-add'),
	path('services/edit/<int:s_id>/', service_edit, name='service-edit'),
	path('services/remove/<int:s_id>/', service_remove, name='service-remove'),

    path('cleaning-programs/list/', cleaning_programs_list, name='cleaning-programs-list'),
	path('cleaning-programs/add/', cleaning_program_add, name='cleaning-program-add'),
	path('cleaning-programs/edit/<int:c_id>/', cleaning_program_edit, name='cleaning-program-edit'),
	path('cleaning-programs/remove/<int:c_id>/', cleaning_program_remove, name='cleaning-program-remove'),

    path('snippets/list/', snippets_list, name='snippets-list'),
    path('get-snippet/ajax/<slug:f_slug>/', get_snippet_ajax, name='get-snippet-ajax'),
	path('snippets/add/', snippet_add, name='snippet-add'),
	path('snippets/edit/<int:s_id>/', snippet_edit, name='snippet-edit'),
	path('snippets/remove/<int:s_id>/', snippet_remove, name='snippet-remove'),

    path('notes/list/', notes_list, name='notes-list'),
	path('notes/add/', note_add, name='note-add'),
	path('notes/edit/<int:n_id>/', note_edit, name='note-edit'),
	path('notes/view/<int:n_id>/', note_view, name='note-view'),
	path('notes/remove/<int:n_id>/', note_remove, name='note-remove'),

	path('contract/template/', contract_template_list, name='contract-template'),

	path('contract-template/list/', contract_template_list, name='contract-template-list'),
    path('contract-template/add/', contract_template_add, name='contract-template-add'),
    path('contract-template/edit/<int:c_id>/', contract_template_edit, name='contract-template-edit'),
    path('contract-template/view/<int:c_id>/', customer_edit, name='contract-template-view'),
    path('contract-template/remove/<int:c_id>/', customer_remove, name='contract-template-remove'),

    path('contract/confirm/<uuid:tc_id>/', contract_confirm, name='contract-confirm'),
    path('contract/confirm-success/', contract_confirm_success, name='contract-confirm-success'),

	path('calendar/show/', calendar, name='calendar-show'),
	path('calendar/calendar-customer-task-remove/<int:td_id>/', calendar_remove, name='calendar-customer-task-remove'),
	path('economy/chart/', economy, name='economy-chart'),
	path('salary/info/', salary, name='salary-info'),



	path('teams/plans/team/<int:t_id>/', admin_team_plans, name='admin-team-plans'),
	path('teams/plans/list/', team_plans, name='team-plans'),
	path('teams/plans/show/ajax/', team_plan_show_ajax, name='team-plan-show-ajax'),
	path('teams/plans/show/plan-map/ajax/', team_plan_show_map_ajax, name='team-plan-map-ajax'),

	path('d/admin-team-plan-form-generate/ajax/', admin_team_plan_form_generate_ajax, name='admin-team-plan-form-generate-ajax'),
	path('d/admin-team-plan-form-change-customer-position-ajax/ajax/<int:cur_cus_ord_id>/',
		admin_team_plan_form_change_customer_position_ajax, name='admin-change-customer-position-ajax'),
	path('d/admin-team-plan-form-customer-ajax/ajax/<int:e_p_id>/<int:l_id>/', admin_team_plan_form_customer_ajax, name='admin-team-plan-form-customer-ajax'),
]

templates/work/admin/cleaning-programs/cleaning-program-add-or-edit.html
{% extends 'main-base.html' %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block title_block %}

{% endblock %}

{% block metatag_block %}

{% endblock %}

{% block page_css_block %}
    <link rel="stylesheet"
          href="{% static 'main/dist/assets/select2/4.0.5/css/select2.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/dist/assets/select2-bootstrap4-theme-master/dist/select2-bootstrap4.css' %}">
{% endblock %}


{% block content_block %}
    <div class="main-content">
        <div class="container-fluid">
            <div class="page-header">
                <h2 class="header-title">{% if cleaning_program_obj %}{% trans 'Cleaning program edit' %} - {{ cleaning_program_obj.name }}{% else %}{% trans 'Cleaning program add' %}{% endif %}</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a href="{% url 'home:dashboard' %}" class="breadcrumb-item"><i
                                class="ti-home p-r-5"></i>{% trans 'Dashboard' %}</a>
                        <a href="{% url 'work:cleaning-programs-list' %}" class="breadcrumb-item">{% trans 'Cleaning programs' %}</a>
                        <span class="breadcrumb-item active">{% if cleaning_program_obj %}{% trans 'Cleaning program edit' %} - {{ cleaning_program_obj.name }}{% else %}{% trans 'Cleaning program add' %}{% endif %}</span>
                    </nav>
                </div>
            </div>
            <div class="card">
                <div class="card-header border bottom">
                    <h4 class="card-title">{% if cleaning_program_obj %}{% trans 'Cleaning program edit' %} - {{ cleaning_program_obj.name }}{% else %}{% trans 'Cleaning program add' %}{% endif %}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 offset-md-1 offset-lg-2 col-md-10 col-lg-8">
                            <form role="form" id="form-validation" method="post">
                                {% csrf_token %}
                                <div id="business-all-div">
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label control-label">{% trans 'Name' %}</label>
                                        <div class="col-sm-10">
                                            {{ cleaning_program_form.name }}
                                            {% if cleaning_program_form.name.errors %}
                                                <div class="alert alert-danger" style="padding: 7px 0;">
                                                    <button style="margin: 5px 10px;" type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                                        ×
                                                    </button>
                                                    <strong>{{ cleaning_program_form.name.errors }}</strong>
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label control-label">{% trans 'Assign service' %}</label>
                                        <div class="col-sm-10">
                                            {{ cleaning_program_form.assign_service }}
                                            {% if cleaning_program_form.assign_service.errors %}
                                                <div class="alert alert-danger" style="padding: 7px 0;">
                                                    <button style="margin: 5px 10px;" type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                                        ×
                                                    </button>
                                                    <strong>{{ cleaning_program_form.assign_service.errors }}</strong>
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <button class="btn btn-gradient-success">{% trans 'Submit' %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block page_js_block %}
{#    <script src="{% static 'main/dist/assets/select2/4.0.5/js/select2.full.min.js' %}"></script>#}
{#<script>#}
{#        $(".select2-single, .select2-multiple").select2({#}
{#            theme: "bootstrap",#}
{#            placeholder: "Select",#}
{#            minimumSelectionSize: 2,#}
{#            maximumSelectionSize: 6,#}
{#            containerCssClass: ':all:'#}
{#        });#}
{#</script>#}
{% endblock %}

templates/work/admin/cleaning-programs/cleaning-programs-list.html
{% extends 'main-base.html' %}
{% load static %}
{% load i18n %}
{% block title_block %}

{% endblock %}

{% block metatag_block  %}

{% endblock %}

{% block page_css_block  %}
    <link rel="stylesheet" href="{% static 'main/dist/assets/vendor/sweetalert/lib/sweet-alert.css' %}"/>
{% endblock %}


{% block content_block  %}
    <div class="main-content">
        <div class="container-fluid">
            <div class="page-header">
                <h2 class="header-title">{% trans 'Cleaning programs list' %}</h2>
                <div class="header-sub-title">
                    <nav class="breadcrumb breadcrumb-dash">
                        <a href="{% url 'home:dashboard' %}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>{% trans 'Dashboard' %}</a>
                        <a href="{% url 'work:cleaning-programs-list' %}" class="breadcrumb-item">{% trans 'Cleaning programs' %}</a>
                        <span class="breadcrumb-item active">{% trans 'Cleaning programs list' %}</span>
                    </nav>
                </div>
                <h2 class="header-title" style="padding-left: 20px;">
                    <button class="btn btn-success btn-rounded" style="margin-bottom: 0;" onclick="window.location='{% url 'work:cleaning-program-add' %}'">
                        + {% trans 'Add new' %}
                    </button>
                </h2>

            </div>
            <form class="row" id="data-list-form" style="margin-bottom: 15px;">
                {% csrf_token %}
                <div class="col-md-6 form-group ">
                    {{ search_form.name }}
                </div>
                <div class="col-md-6 form-group ">
                    {{ search_form.assign_service }}
                </div>
                <button type="button" class="col-md-12 btn btn-success"
                        onclick="searchForm();">{% trans 'Search' %}</button>
            </form>
            <div class="card">
                <div class="card-body">

                    <div class="table-overflow" id="data-list-main-content">
                        <div class='text-center'>
                            <img style='margin: 10px auto;'
                                 src="{% static 'main/dist/assets/images/loading-gif-transparent-10.gif' %}"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block page_js_block  %}

    <script src="{% static 'main/dist/assets/vendor/sweetalert/lib/sweet-alert.js' %}"></script>
    <script>
        var data_list_main_content = $('#data-list-main-content');
        var ajax_loader_url = '{% static 'main/dist/assets/images/loading-gif-transparent-10.gif' %}';
        function searchForm() {
            data_list_main_content.html("<div class='text-center'><img style='margin: 10px auto;' src='" + ajax_loader_url + "'/></div>");
            $.post("", $('#data-list-form').serialize())
                .done(function (data) {
                    data_list_main_content.html(data['result'])
                });
        }
        $(document).ready(function () {
            searchForm();
        });
    </script>
    <script>
        function removeItem($id,$url) {

			swal({
				title: "{% trans 'Are you sure' %}?",
				text: "{% trans 'You will be able to recover this data' %}!",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "{% trans 'Yes, sure' %} !",
				cancelButtonText: "{% trans 'No, cancel' %} !",
				closeOnConfirm: false,
				closeOnCancel: false
			},
		  function(isConfirm){
				if (isConfirm) {
                    $.get( $url, {} )
                      .done(function( data ) {
                        if (data['message_code'] == 1){
                            $('#data-list-item-'+$id).remove();
					        swal("{% trans 'Activated' %}!", data['message'], "success");
                        }else if (data['message_code'] == 2) {
                            $('#data-list-item-'+$id).remove();
					        swal("{% trans 'Deleted' %}!", data['message'], "success");
                        }else{
                            swal("Cancelled", data['message'], "error");
                        }
                      });
				} else {
					swal("{% trans 'Cancelled' %}", "{% trans 'You have cancelled' %} !", "error");
				}
			});


        }
    </script>

    
{% endblock %}